**1.** Import the numpy package under the name np

In [1]:
import numpy as np

**2.** Print the numpy version and the configuration

In [3]:
np.__version__

'1.19.2'

**3.** Create a null vector of size 10

In [5]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**4.** How to find the memory size of any array

In [13]:
x = np.zeros((10, 10))
print('%d size in bytes' % (x.size * x.itemsize))

800 size in bytes


**5.** How to get the documentation of the numpy add function from the command line?

In [16]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

**6.** Create a null vector of size 10 but the fifth value which is 1

In [20]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**7.** Create a vector with values ranging from 10 to 49

In [23]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**8.** Reverse a vector (first element becomes last)

In [24]:
np.arange(10, 50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

**9.** Create a 3x3 matrix with values ranging from 0 to 8

In [26]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**10.** Find indices of non-zero elements from [1,2,0,0,4,0]

In [27]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

**11.** Create a 3x3 identity matrix

In [30]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**12.** Create a 3x3x3 array with random values

In [34]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.22331501 0.68483898 0.94502008]
  [0.09957864 0.35136071 0.78999103]
  [0.19556256 0.24020865 0.87538278]]

 [[0.49382559 0.3792897  0.72699793]
  [0.69211547 0.78247059 0.6330229 ]
  [0.48193297 0.17501716 0.19388823]]

 [[0.57005031 0.39793304 0.71353404]
  [0.88907725 0.40071035 0.73155695]
  [0.69388435 0.98975874 0.94392788]]]


**13.** Create a 10x10 array with random values and find the minimum and maximum values

In [37]:
x = np.random.random(100).reshape(10,10)

In [38]:
x_min, x_max = x.min(), x.max()

In [39]:
print(x_min)
print(x_max)

0.009287481357324934
0.9733005159408132


**14.** Create a random vector of size 30 and find the mean value

In [41]:
x = np.random.random(30)

In [42]:
x.mean()

0.4452255008818671

**15.** Create a 2d array with 1 on the border and 0 inside

In [46]:
x = np.ones((10,10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**16.** How to add a border (filled with 0's) around an existing array?

In [48]:
x = np.ones((5,5))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [61]:
a = np.ones((4, 4))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


**17.** What is the result of the following expression? 

In [81]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


**18.** Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [83]:
np.diag(1+np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

**19.** Create a 8x8 matrix and fill it with a checkerboard pattern

In [85]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**20.** Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 

In [89]:
print(np.unravel_index(99, (6, 7, 8)))

(1, 5, 3)


**21.** Create a checkerboard 8x8 matrix using the tile function

In [99]:
x = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**22.** Normalize a 5x5 random matrix

In [100]:
df= np.random.random((3,3))
print(df)

[[0.56705542 0.19296274 0.16837286]
 [0.17644595 0.84345404 0.2500015 ]
 [0.42405382 0.22265551 0.8634482 ]]


In [101]:
dfmax, dfmin = df.max(), df.min()
df = (df - dfmin)/(dfmax - dfmin)
print(df)

[[0.5735818  0.0353773  0.        ]
 [0.0116147  0.97123454 0.11743856]
 [0.3678464  0.07809606 1.        ]]
